import { PageCategoryType, Teamtype } from "@/types/type";

export const TeamData: Teamtype[] = [
  {
    id: 1,
    name: "Lehel",
    image: "/images/team1.jpg",
    role: "Owner",
  },
  {
    id: 2,
    name: "John Doe",
    image: "/images/team2.jpg",
    role: "CEO",
  },
  {
    id: 3,
    name: "John Doe",
    image: "/images/team3.jpg",
    role: "CEO",
  },
  {
    id: 4,
    name: "Alex doe",
    image: "/images/team4.jpg",
    role: "CEO",
  },
  {
    id: 5,
    name: "John Doe",
    image: "/images/team5.jpg",
    role: "CEO",
  },
  {
    id: 6,
    name: "John Doe",
    image: "/images/team6.jpg",
    role: "CEO",
  },
  {
    id: 7,
    name: "John Doe",
    image: "/images/team7.jpg",
    role: "CEO",
  },
  {
    id: 8,
    name: "John Doe",
    image: "/images/team8.jpg",
    role: "CEO",
  },
  {
    id: 9,
    name: "John Doe",
    image: "/images/team9.jpg",
    role: "CEO",
  },
  {
    id: 10,
    name: "John Doe",
    image: "/images/team10.jpg",
    role: "CEO",
  },
];

export const CategoryData: PageCategoryType[] = [
  {
    id: 1,
    name: "Roof Systems",
    img: "/images/category1.jpg",
    slug: "roof-systems",
    subpages: [
      {
        image: "/images/bgroof.jpg",
        title: "Classic Carpentry",
        slug: "classic-carpentry",
        description: [
          "At Carpenter Express, we take pride in our classic carpentry skills, which have been honed over decades. Our expertise in traditional woodwork allows us to create stunning, durable structures that stand the test of time. From intricate joinery to robust timber frames, our craftsmanship reflects a deep respect for the art of woodworking.",
        ],
        gallerySections: [
          {
            galleryTitle: "Roofing Projects",
            images: [
              "/images/Roof Systems/TraditionalCarpenter/roofing/1.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/2.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/3.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/4.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/5.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/7.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/8.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/9.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/10.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/11.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/12.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/13.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/14.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/15.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/16.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/17.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/18.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/19.jpg",
              "/images/Roof Systems/TraditionalCarpenter/roofing/20.jpg",
            ],
          },
          {
            galleryTitle: "Water Towers",
            images: [
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/1.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/2.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/3.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/4.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/5.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/6.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/7.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/8.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/9.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/10.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/11.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Water Tower/12.jpg",
            ],
          },
          {
            galleryTitle: "Garages",
            images: [
              "/images/Roof Systems/TraditionalCarpenter/Garage/1.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Garage/2.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Garage/3.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Garage/4.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Garage/5.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Garage/6.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Garage/7.jpg",
              "/images/Roof Systems/TraditionalCarpenter/Garage/8.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/bgnail.jpg",
        title: "Nail Plate Trusses",
        slug: "nail-plate-trusses",
        description: [
          "Nail plate trusses are a modern solution for creating strong, lightweight roof structures. At Carpenter Express, we specialize in designing and manufacturing these trusses to meet the specific needs of each project. Our nail plate trusses are engineered for durability and efficiency, making them ideal for both residential and commercial applications.",
          "We use high-quality materials and advanced manufacturing techniques to ensure that our trusses provide excellent structural support while being cost-effective. Whether you need standard designs or custom solutions, our team is ready to assist you.",
        ],
        gallerySections: [
          {
            galleryTitle: "Roof Trusses",
            images: [
              "/images/Roof Systems/Nail Plate Trusses/1.jpg",
              "/images/Roof Systems/Nail Plate Trusses/2.jpg",
              "/images/Roof Systems/Nail Plate Trusses/3.jpg",
              "/images/Roof Systems/Nail Plate Trusses/4.jpg",
              "/images/Roof Systems/Nail Plate Trusses/5.jpg",
              "/images/Roof Systems/Nail Plate Trusses/6.jpg",
              "/images/Roof Systems/Nail Plate Trusses/7.jpg",
              "/images/Roof Systems/Nail Plate Trusses/8.jpg",
              "/images/Roof Systems/Nail Plate Trusses/9.jpg",
              "/images/Roof Systems/Nail Plate Trusses/10.jpg",
              "/images/Roof Systems/Nail Plate Trusses/11.jpg",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Furniture",
    img: "/images/category2.jpg",
    slug: "furniture",
    subpages: [
      {
        image: "/images/bgnail.jpg",
        title: "Social Spaces",
        slug: "social-spaces",
        description: [
          "Bringing children and adults together to explore nature is one of our favorite ideas. At Carpenter Express, we design educational trails that highlight the unique features of each landscape, using thoughtfully crafted wooden pathways. Our goal is to create immersive experiences through well-placed rest areas, observation points, and informative displays.",
          "As passionate nature-lovers and skilled craftsmen, we believe that understanding the local environment and culture is just as important as expert woodworking and landscaping. With the natural richness of our region, we’re excited to continue collaborating on meaningful, high-quality trail projects.",
        ],

        gallerySections: [
          {
            galleryTitle: "Roof Trusses",
            images: [
              "/images/Furniture/Social/Kindergarten of Madefalva/1.jpg",
              "/images/Furniture/Social/Kindergarten of Madefalva/2.jpg",
              "/images/Furniture/Social/Kindergarten of Madefalva/3.jpg",
              "/images/Furniture/Social/Kindergarten of Madefalva/4.jpg",
              "/images/Furniture/Social/Kindergarten of Madefalva/5.jpg",
              "/images/Furniture/Social/Kindergarten of Madefalva/6.jpg",
              "/images/Furniture/Social/Kindergarten of Madefalva/7.jpg",
            ],
          },
          {
            galleryTitle: "Furniture Store",
            images: [
              "/images/Furniture/Social/Furniture Store/1.jpg",
              "/images/Furniture/Social/Furniture Store/2.jpg",
            ],
          },
          {
            galleryTitle: "Day Care of Madefalva",
            images: [
              "/images/Furniture/Social/Day Care of Madefalva/1.jpg",
              "/images/Furniture/Social/Day Care of Madefalva/2.jpg",
              "/images/Furniture/Social/Day Care of Madefalva/3.jpg",
              "/images/Furniture/Social/Day Care of Madefalva/4.jpg",
              "/images/Furniture/Social/Day Care of Madefalva/5.jpg",
              "/images/Furniture/Social/Day Care of Madefalva/6.jpg",
              "/images/Furniture/Social/Day Care of Madefalva/7.jpg",
            ],
          },
          {
            galleryTitle: "Day Care of Madefalva",
            images: [
              "/images/Furniture/Social/Day Care of Madefalve/1.jpg",
              "/images/Furniture/Social/Day Care of Madefalve/2.jpg",
              "/images/Furniture/Social/Day Care of Madefalve/3.jpg",
              "/images/Furniture/Social/Day Care of Madefalve/4.jpg",
              "/images/Furniture/Social/Day Care of Madefalve/5.jpg",
              "/images/Furniture/Social/Day Care of Madefalve/6.jpg",
              "/images/Furniture/Social/Day Care of Madefalve/7.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/kitchen-furniture.jpg",
        title: "Kitchen Design",
        slug: "kitchen-design",
        description: [
          "The kitchen is the heart of every home, a space that blends functionality with personal style. At Carpenter Express, we understand that today’s kitchens are more than just places to cook; they must meet modern expectations for design, efficiency, and comfort.",
          "We collaborate closely with each client to design fully customized kitchens tailored to their needs. From selecting high-quality materials to creating professional visualizations, we ensure every detail is thoughtfully planned including color schemes, lighting, and layout.",
          "To simplify the process, we also supply kitchen equipment and accessories directly, helping integrate appliances seamlessly into the design. Whether you're seeking a cost-effective option or a premium bespoke setup, our handcrafted kitchen solutions are made to be practical, beautiful, and built to last.",
        ],
        gallerySections: [
          {
            galleryTitle: "Kitchen No 1",
            images: [
              "/images/Furniture/Kitchen/1.jpg",
              "/images/Furniture/Kitchen/2.jpg",
              "/images/Furniture/Kitchen/3.jpg",
              "/images/Furniture/Kitchen/4.jpg",
              "/images/Furniture/Kitchen/5.jpg",
              "/images/Furniture/Kitchen/6.jpg",
              "/images/Furniture/Kitchen/7.jpg",
              "/images/Furniture/Kitchen/8.jpg",
            ],
          },
          {
            galleryTitle: "Kitchen No 2",
            images: [
              "/images/Furniture/Kitchen/9.jpg",
              "/images/Furniture/Kitchen/10.jpg",
              "/images/Furniture/Kitchen/11.jpg",
              "/images/Furniture/Kitchen/12.jpg",
              "/images/Furniture/Kitchen/13.jpeg",
              "/images/Furniture/Kitchen/14.jpeg",
              "/images/Furniture/Kitchen/15.jpeg",
              "/images/Furniture/Kitchen/16.jpeg",
            ],
          },
          {
            galleryTitle: "Kitchen No 3",
            images: [
              "/images/Furniture/Kitchen/17.jpg",
              "/images/Furniture/Kitchen/18.jpg",
              "/images/Furniture/Kitchen/19.jpg",
              "/images/Furniture/Kitchen/20.jpg",
              "/images/Furniture/Kitchen/21.jpg",
              "/images/Furniture/Kitchen/22.jpg",
              "/images/Furniture/Kitchen/23.jpg",
              "/images/Furniture/Kitchen/24.jpg",
            ],
          },
          {
            galleryTitle: "Kitchen No 4",
            images: [
              "/images/Furniture/Kitchen/25.jpg",
              "/images/Furniture/Kitchen/26.jpg",
              "/images/Furniture/Kitchen/27.jpg",
              "/images/Furniture/Kitchen/28.jpg",
              "/images/Furniture/Kitchen/29.jpg",
              "/images/Furniture/Kitchen/30.jpg",
              "/images/Furniture/Kitchen/31.jpg",
              "/images/Furniture/Kitchen/32.jpg",
            ],
          },
          {
            galleryTitle: "Kitchen No 5",
            images: [
              "/images/Furniture/Kitchen/33.jpg",
              "/images/Furniture/Kitchen/34.jpg",
              "/images/Furniture/Kitchen/35.jpg",
              "/images/Furniture/Kitchen/36.jpg",
              "/images/Furniture/Kitchen/37.jpg",
              "/images/Furniture/Kitchen/38.jpg",
              "/images/Furniture/Kitchen/39.jpg",
              "/images/Furniture/Kitchen/40.jpg",
            ],
          },
          {
            galleryTitle: "Kitchen No 6",
            images: [
              "/images/Furniture/Kitchen/41.jpg",
              "/images/Furniture/Kitchen/42.jpg",
              "/images/Furniture/Kitchen/43.jpg",
              "/images/Furniture/Kitchen/44.jpg",
              "/images/Furniture/Kitchen/45.jpg",
              "/images/Furniture/Kitchen/46.jpg",
              "/images/Furniture/Kitchen/47.jpg",
              "/images/Furniture/Kitchen/48.jpg",
            ],
          },
          {
            galleryTitle: "Kitchen No 7",
            images: [
              "/images/Furniture/Kitchen/49.jpg",
              "/images/Furniture/Kitchen/50.jpg",
              "/images/Furniture/Kitchen/51.jpg",
              "/images/Furniture/Kitchen/52.jpg",
              "/images/Furniture/Kitchen/53.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/urban-furniture.jpg",
        title: "Urban Projects",
        slug: "urban-projects",
        description: [
          "When creating outdoor furniture and structures, durability is our top priority. At Carpenter Express, we harness wood’s natural resistance to the elements while ensuring each piece fits seamlessly into its environment  both functionally and visually.",
          "Understanding the purpose of a space guides our material choices and design. Outdoor furniture is always a balance between the client’s vision and what nature allows  and we bridge that gap with expert craftsmanship. Our in-house tinsmiths and metalworkers reinforce each structure for lasting stability and weather resistance.",
          "We’re always open to collaboration with architects, designers, and clients on unique urban woodwork projects that demand both strength and style.",
        ],
        gallerySections: [
          {
            galleryTitle: "Siculeni Park",
            images: [
              "/images/Furniture/Urber/SICULENI PARK/1.jpg",
              "/images/Furniture/Urber/SICULENI PARK/2.jpg",
              "/images/Furniture/Urber/SICULENI PARK/3.jpg",
              "/images/Furniture/Urber/SICULENI PARK/4.jpg",
              "/images/Furniture/Urber/SICULENI PARK/5.jpg",
              "/images/Furniture/Urber/SICULENI PARK/6.jpg",
              "/images/Furniture/Urber/SICULENI PARK/7.jpg",
            ],
          },
          {
            galleryTitle: "Road Of Siculicidium",
            images: [
              "/images/Furniture/Urber/ROAD OF SICULICIDIUM/1.jpg",
              "/images/Furniture/Urber/ROAD OF SICULICIDIUM/2.jpg",
              "/images/Furniture/Urber/ROAD OF SICULICIDIUM/3.jpg",
              "/images/Furniture/Urber/ROAD OF SICULICIDIUM/4.jpg",
            ],
          },
          {
            galleryTitle: "Wild Ferenc Memorial Road",
            images: [
              "/images/Furniture/Urber/WILD FERENC MEMORIAL ROAD/1.jpg",
              "/images/Furniture/Urber/WILD FERENC MEMORIAL ROAD/2.jpg",
              "/images/Furniture/Urber/WILD FERENC MEMORIAL ROAD/3.jpg",
              "/images/Furniture/Urber/WILD FERENC MEMORIAL ROAD/4.jpg",
            ],
          },
          {
            galleryTitle: "Wooden Roof 3",
            images: [
              "/images/Furniture/Urber/WOODEN ROOF 3/1.jpg",
              "/images/Furniture/Urber/WOODEN ROOF 3/2.jpg",
              "/images/Furniture/Urber/WOODEN ROOF 3/3.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/other-furniture.jpg",
        title: "Custom Builds",
        slug: "custom-builds",
        description: [
          "Not every piece of furniture follows traditional rules  and that’s where our creativity shines. At Carpenter Express, we take on custom requests that demand more than just standard design. Whether it’s creating pieces resistant to wear and humidity, fitting unique dimensions, or achieving a bold, exclusive aesthetic, we tailor every detail to meet the client’s vision.",
          "Through in-depth consultations and on-site assessments, our team including designers, constructors, and clients  collaborates to bring each idea to life. Every tailored project is guided by detailed visual plans, careful material selection, and our deep technical expertise.",
          "For us, every complex request is an opportunity to innovate, push boundaries, and deliver something truly exceptional.",
        ],
        gallerySections: [
          {
            galleryTitle: "bedroom Projects",
            images: [
              "/images/Furniture/Other/Bedroom/1.jpg",
              "/images/Furniture/Other/Bedroom/2.jpg",
              "/images/Furniture/Other/Bedroom/3.jpg",
              "/images/Furniture/Other/Bedroom/4.jpg",
            ],
          },
          {
            galleryTitle: "Living Furniture",
            images: [
              "/images/Furniture/Other/Living Room/1.jpeg",
              "/images/Furniture/Other/Living Room/2.jpeg",
              "/images/Furniture/Other/Living Room/3.jpeg",
              "/images/Furniture/Other/Living Room/4.jpeg",
            ],
          },
          {
            galleryTitle: "Office Furniture",
            images: [
              "/images/Furniture/Other/Office/1.jpg",
              "/images/Furniture/Other/Office/2.jpg",
              "/images/Furniture/Other/Office/3.jpg",
              "/images/Furniture/Other/Office/4.jpg",
            ],
          },
          {
            galleryTitle: "Table Furniture",
            images: [
              "/images/Furniture/Other/Table/1.jpg",
              "/images/Furniture/Other/Table/2.jpg",
              "/images/Furniture/Other/Table/3.jpg",
              "/images/Furniture/Other/Table/4.jpg",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Stairs",
    img: "/images/category3.jpg",
    slug: "stair",
    subpages: [
      {
        image: "/images/wooden-stairs.jpg",
        title: "View Stair Gallery",
        slug: "view-stair-gallery",
        description: [
          "At Carpenter Express, crafting stairs is more than a tradition  it's a legacy. Our family has dedicated three generations to mastering stair design, combining deep-rooted craftsmanship with continuous innovation. From classic supported and built-in designs to elegant spiral staircases, our work reflects decades of refinement in Romania and Transylvania.",
          "Every staircase we build is tailored to the client's space and style. We offer a wide range of materials, advanced surface treatments, integrated lighting, and customized design options to ensure each project is both functional and visually striking.",
          "With detailed assessments, expert consultation, and precision design, we deliver seamless production and installation. Curious about how your staircase might look? Explore our Virtual Stair Studio on our website and bring your vision to life in just a few clicks.",
        ],
        gallerySections: [
          {
            galleryTitle: "Stairs No 1",
            images: [
              "/images/Stairs/1.jpg",
              "/images/Stairs/2.jpg",
              "/images/Stairs/3.jpg",
              "/images/Stairs/4.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 2",
            images: [
              "/images/Stairs/5.jpg",
              "/images/Stairs/6.jpg",
              "/images/Stairs/7.jpg",
              "/images/Stairs/8.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 3",
            images: [
              "/images/Stairs/9.jpg",
              "/images/Stairs/10.jpg",
              "/images/Stairs/11.jpg",
              "/images/Stairs/12.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 4",
            images: [
              "/images/Stairs/13.jpg",
              "/images/Stairs/14.jpg",
              "/images/Stairs/15.jpg",
              "/images/Stairs/16.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 5",
            images: [
              "/images/Stairs/17.jpg",
              "/images/Stairs/18.jpg",
              "/images/Stairs/19.jpg",
              "/images/Stairs/20.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 6",
            images: [
              "/images/Stairs/21.jpg",
              "/images/Stairs/22.jpg",
              "/images/Stairs/23.jpg",
              "/images/Stairs/24.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 7",
            images: [
              "/images/Stairs/25.jpg",
              "/images/Stairs/26.jpg",
              "/images/Stairs/27.jpg",
              "/images/Stairs/28.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 8",
            images: [
              "/images/Stairs/29.jpg",
              "/images/Stairs/30.jpg",
              "/images/Stairs/31.jpg",
              "/images/Stairs/32.jpg",
            ],
          },
          {
            galleryTitle: "Stairs No 9",
            images: [
              "/images/Stairs/33.jpg",
              "/images/Stairs/34.jpg",
              "/images/Stairs/35.jpg",
              "/images/Stairs/36.jpg",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Wood Architecture",
    img: "/images/category4.jpg",
    slug: "wood-architecture",
    subpages: [
      {
        image: "/images/prefab-construction.jpg",
        title: "Prefab Builds",
        slug: "prefab-builds",
        description: [
          "“You can dream, create, design, and build the most wonderful place in the world. But it requires people to make the dream a reality.” – Walt Disney",
          "At Carpenter Express, we turn ideas into reality through efficient and precise prefab construction. By combining thoughtful design with expert craftsmanship, we deliver structures that are both functional and beautifully tailored to your vision. Our team ensures that every element   from concept to installation is handled with care, so your dream space comes to life seamlessly and sustainably.",
        ],
        gallerySections: [
          {
            galleryTitle: "Panoramic Cabins",
            images: [
              "/images/Wood Architecture/Prefab Construction/1.jpg",
              "/images/Wood Architecture/Prefab Construction/2.jpg",
              "/images/Wood Architecture/Prefab Construction/3.jpg",
              "/images/Wood Architecture/Prefab Construction/4.jpg",
              "/images/Wood Architecture/Prefab Construction/5.jpg",
              "/images/Wood Architecture/Prefab Construction/6.jpg",
              "/images/Wood Architecture/Prefab Construction/7.jpg",
              "/images/Wood Architecture/Prefab Construction/8.jpg",
              "/images/Wood Architecture/Prefab Construction/9.jpg",
              "/images/Wood Architecture/Prefab Construction/10.jpg",
              "/images/Wood Architecture/Prefab Construction/11.jpg",
              "/images/Wood Architecture/Prefab Construction/12.jpg",
              "/images/Wood Architecture/Prefab Construction/13.jpg",
              "/images/Wood Architecture/Prefab Construction/14.jpg",
              "/images/Wood Architecture/Prefab Construction/15.jpg",
              "/images/Wood Architecture/Prefab Construction/16.jpg",
              "/images/Wood Architecture/Prefab Construction/17.jpg",
              "/images/Wood Architecture/Prefab Construction/18.jpg",
              "/images/Wood Architecture/Prefab Construction/19.jpg",
              "/images/Wood Architecture/Prefab Construction/20.jpg",
              "/images/Wood Architecture/Prefab Construction/21.jpg",
              "/images/Wood Architecture/Prefab Construction/22.jpg",
              "/images/Wood Architecture/Prefab Construction/23.jpg",
              "/images/Wood Architecture/Prefab Construction/24.jpg",
              "/images/Wood Architecture/Prefab Construction/25.jpg",
              "/images/Wood Architecture/Prefab Construction/26.jpg",
              "/images/Wood Architecture/Prefab Construction/27.jpg",
              "/images/Wood Architecture/Prefab Construction/28.jpg",
              "/images/Wood Architecture/Prefab Construction/29.jpg",
              "/images/Wood Architecture/Prefab Construction/30.jpg",
              "/images/Wood Architecture/Prefab Construction/31.jpg",
              "/images/Wood Architecture/Prefab Construction/32.jpg",
              "/images/Wood Architecture/Prefab Construction/33.jpg",
              "/images/Wood Architecture/Prefab Construction/34.jpg",
              "/images/Wood Architecture/Prefab Construction/35.jpg",
              "/images/Wood Architecture/Prefab Construction/36.jpg",
              "/images/Wood Architecture/Prefab Construction/37.jpg",
              "/images/Wood Architecture/Prefab Construction/38.jpg",
              "/images/Wood Architecture/Prefab Construction/39.jpg",
              "/images/Wood Architecture/Prefab Construction/40.jpg",
              "/images/Wood Architecture/Prefab Construction/41.jpg",
              "/images/Wood Architecture/Prefab Construction/42.jpg",
              "/images/Wood Architecture/Prefab Construction/43.jpg",
              "/images/Wood Architecture/Prefab Construction/44.jpg",
              "/images/Wood Architecture/Prefab Construction/45.jpg",
              "/images/Wood Architecture/Prefab Construction/46.jpg",
              "/images/Wood Architecture/Prefab Construction/47.jpg",
              "/images/Wood Architecture/Prefab Construction/48.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/timber-construction.jpg",
        title: "Timber Structures",
        slug: "timber-structures",
        description: [
          "“You can dream, create, design, and build the most wonderful place in the world. But it requires people to make the dream a reality.” – Walt Disney",
          "At Carpenter Express, we believe in the strength and beauty of timber. Our timber construction projects are rooted in tradition and brought to life with modern techniques. Whether it’s a structural frame, a bespoke cabin, or a custom wood feature, we combine design excellence with skilled craftsmanship to build durable, eco-conscious spaces that feel as natural as they are refined.",
        ],
        gallerySections: [
          {
            galleryTitle: "Roof Construction",
            images: [
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/1.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/2.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/3.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/4.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/5.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/6.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/7.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/8.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/9.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/10.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/11.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/12.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/13.jpg",
              "/images/Wood Architecture/Timber Construction/Roof Construction and Roofing/14.jpg",
            ],
          },
          {
            galleryTitle: "Support Mounting",
            images: [
              "/images/Wood Architecture/Timber Construction/Support Mounting/1.jpg",
              "/images/Wood Architecture/Timber Construction/Support Mounting/2.jpg",
              "/images/Wood Architecture/Timber Construction/Support Mounting/3.jpg",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Specialized Services",
    img: "/images/category5.jpg",
    slug: "specialized-services",
    subpages: [
      {
        image: "/images/cellulose-insulation.jpg",
        title: "THERMOFLOC® Cellulose Building Insulation",
        slug: "thermofloc-cellulose-insulation",
        description: [
          "THERMOFLOC® is more than just insulation, it's a commitment to eco-friendly and efficient building. Made entirely from recycled paper, this cellulose-based insulation is 100% organic and produced with minimal energy consumption. Recognized with the Natureplus® quality label, THERMOFLOC® stands out for its sustainability, safety, and excellent performance.",
        ],
        gallerySections: [
          {
            galleryTitle: "Photo",
            images: [
              "/images/Services/Thermofloc Cellulose Insulation/1.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/2.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/3.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/4.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/5.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/6.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/7.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/8.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/9.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/10.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/11.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/12.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/13.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/14.jpg",
              "/images/Services/Thermofloc Cellulose Insulation/15.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/planning-and-3d-measuring.jpg",
        title: "CNC Joinery Planning",
        slug: "cnc-joinery-planning",
        description: [
          "For the best results, please share scaled PDF plans of your project. If available, we also accept files in .IFC, .DXF, or .DWG formats.",
          "No plans? No problem. Even if you only have a concept, our team will help you design and produce it. Every CNC-manufactured piece comes with detailed assembly instructions and a product layout, making installation quick and hassle-free.",
          "Let’s bring your ideas to life  with precision, creativity, and craftsmanship.",
        ],
        gallerySections: [
          {
            galleryTitle: "3D Planning",
            images: [
              "/images/Services/Planning $ Cnc Joinery/3D Planing/1.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/2.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/3.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/4.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/5.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/6.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/7.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/8.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/9.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/10.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/11.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/12.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/13.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/14.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/15.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/16.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/17.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/18.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/19.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/20.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/21.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/22.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/23.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/24.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/25.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/26.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/27.jpg",
              "/images/Services/Planning $ Cnc Joinery/3D Planing/28.jpg",
            ],
          },
          {
            galleryTitle: "CNC Joinery",
            images: [
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/1.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/2.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/3.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/4.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/5.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/6.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/7.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/8.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/9.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/10.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/11.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/12.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/13.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/14.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/15.jpg",
              "/images/Services/Planning $ Cnc Joinery/CNC Joinery/16.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/3d-measuring.jpg",
        title: "3D Measurement",
        slug: "3d-measuring",
        description: [
          "Our 3D measurement services utilize cutting-edge technology to ensure precise measurements for all your carpentry needs. This advanced approach allows us to create accurate models and plans, enhancing the quality and efficiency of our projects.",
        ],
        gallerySections: [
          {
            galleryTitle: "Carpentry 3D Measurement",
            images: [
              "/images/Services/3d Measuring/0.jpg",
              "/images/Services/3d Measuring/1.jpg",
              "/images/Services/3d Measuring/2.jpg",
              "/images/Services/3d Measuring/3.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/seam-roll-forming.jpg",
        title: "Seam Forming",
        slug: "seam-forming",
        description: [
          "We specialize in profiling flat and strip sheet metal for corrugated coverings, including parallel and trapezoidal edge designs.",
        ],
        gallerySections: [
          {
            galleryTitle: "Seam Roll-Forming",
            images: [
              "/images/Services/Seam Roll-Forming/1.jpg",
              "/images/Services/Seam Roll-Forming/2.jpg",
              "/images/Services/Seam Roll-Forming/3.jpg",
              "/images/Services/Seam Roll-Forming/4.jpg",
              "/images/Services/Seam Roll-Forming/5.jpg",
              "/images/Services/Seam Roll-Forming/6.jpg",
              "/images/Services/Seam Roll-Forming/7.jpg",
              "/images/Services/Seam Roll-Forming/8.jpg",
              "/images/Services/Seam Roll-Forming/9.jpg",
              "/images/Services/Seam Roll-Forming/10.jpg",
              "/images/Services/Seam Roll-Forming/11.jpg",
              "/images/Services/Seam Roll-Forming/12.jpg",
              "/images/Services/Seam Roll-Forming/13.jpg",
              "/images/Services/Seam Roll-Forming/14.jpg",
              "/images/Services/Seam Roll-Forming/15.jpg",
              "/images/Services/Seam Roll-Forming/16.jpg",
              "/images/Services/Seam Roll-Forming/17.jpg",
              "/images/Services/Seam Roll-Forming/18.jpg",
              "/images/Services/Seam Roll-Forming/19.jpg",
              "/images/Services/Seam Roll-Forming/20.jpg",
            ],
          },
        ],
      },
      {
        image: "/images/crane-service.jpg",
        title: "Crane Operations",
        slug: "crane-operations",
        description: [
          "Professional carpenter crane rental with operator and on-site delivery. Compact and efficient, the crane weighs just 3,500 kg and is mounted on wheels ideal for maneuvering in tight spaces without causing damage to the surroundings.",
        ],
        gallerySections: [
          {
            galleryTitle: "Crane Trailer",
            images: [
              "/images/Services/Crane Service/1.jpg",
              "/images/Services/Crane Service/2.jpg",
              "/images/Services/Crane Service/3.jpg",
              "/images/Services/Crane Service/4.jpg",
              "/images/Services/Crane Service/5.jpg",
              "/images/Services/Crane Service/6.jpg",
              "/images/Services/Crane Service/7.jpg",
            ],
          },
        ],
      },
    ],
  },
];
